"""
Django settings for Discord_Taher project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4h#b!8e2^=0!x48lhu=t+!%583dvv5lz65wo8*1+iz1h9c%yi&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['*']

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

AUTH_USER_MODEL = "App.MyUser"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "App",
    'rest_framework',
    "corsheaders",
    'drf_yasg',
    'channels',
   
]
# LOGIN_URL = 'login'  # This should be the URL name of your login page.
# LOGIN_REDIRECT_URL = 'dashboard_view'  # Redirect users to the dashboard after login.



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "Discord_Taher.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "Discord_Taher.wsgi.application"
ASGI_APPLICATION = 'Discord_Taher.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'mysql.connector.django', 
#         'NAME': 'breakoutDB_live',  
#         'USER': 'breakout_user',  
#         'PASSWORD': 'Mobilo/tte56',  
#         'HOST': '3.234.60.184', 
#         'PORT': '3306',  
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', 
#         'NAME': 'mySQL',  
#         'USER': 'admin',  
#         'PASSWORD': 'TRVVNwrt',  
#         'HOST': 'mysql-164782-0.cloudclusters.net', 
#         'PORT': '10013',  
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', 
        'NAME': 'postgres',  
        'USER': 'dbmasteruser',  
        'PASSWORD': 'C0kOz}?eckm{TRn>wM#MX#:2X_&D8$7;',  
        'HOST': 'ls-7825951988fd49d49303d98bfa3a5de51d2be36b.cxsi8io64vei.ap-south-1.rds.amazonaws.com', 
        'PORT': '5432',  
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'assits')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# smtp email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'tahervag@gmail.com'
EMAIL_HOST_PASSWORD = 'qxlakwqmqhjlunio'
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_CA_BUNDLE = '/path/to/ca_bundle.pem'


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS= False
CSRF_TRUSTED_ORIGINS =[
    "https://py-discordbotwebapp.mobiloitte.io",
    "https://21mtechnicals.com",
    "https://admin.21mtechnicals.com",
    "https://bass-mint-cricket.ngrok-free.app"
]
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # or 'channels.layers.RedisChannelLayer' for production
    },
}